openapi: 3.0.0
info:
    description: Ravito's Frigo API
    version: 1.0.0
    title: Frigo API
paths:
    /ping:
        get:
            description: Pong
            responses:
                200:
                    description: Pong
                    content:
                        application/json:
                            schema:
                                type: string
    /v1/foods:
        get:
            description: List all foods
            responses:
                200:
                    description: List of all foods OK
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/FoodList'
        post:
            description: Add new food
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/Food'
            responses:
                201:
                    description: Food successfully created
                400:
                    $ref: '#/components/responses/IncorrectPayload'
                500:
                    description: Data could not be processed
    /v1/foods/{id}:
        parameters:
            - in: path
              name: id
              required: true
              schema:
                  type: integer
              description: ID of corresponding food
        get:
            description: Retrieve the corresponding food
            responses:
                200:
                    description: Retrieve the corresponding food
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/Food'
                404:
                    $ref: '#/components/responses/ResourceNotFound'
        put:
            description: Update the corresponding food
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/Food'
            responses:
                200:
                    description: Food was successfully updated
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/Food'
                400:
                    $ref: '#/components/responses/IncorrectPayload'
                404:
                    $ref: '#/components/responses/ResourceNotFound'
        delete:
            description: Removes the corresponding food
            responses:
                204:
                    description: Successfully deletes the corresponding food
                404:
                    $ref: '#/components/responses/ResourceNotFound'

components:
    schemas:
        Food:
            type: object
            properties:
                id:
                    type: integer
                    nullable: false
                name:
                    type: string
                    nullable: false
                ingestion:
                    type: string
                    enum:
                        - drink
                        - eat
                carbs:
                    type: integer
                    nullable: true
                calories:
                    type: integer
                    nullable: true
                proteins:
                    type: integer
                    nullable: true
                electrolytes:
                    type: boolean
                    nullable: false
                comment:
                    type: string
                    nullable: true
        FoodList:
            type: object
            properties:
                foods:
                    type: array
                    items:
                        $ref: '#/components/schemas/Food'
    responses:
        IncorrectPayload:
            description: Incorrect payload
        ResourceNotFound:
            description: Resource not found
